/*
	Task 3: 
	Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue.
*/

SELECT 
    c.name AS CategoryName,
    SUM(ip.quantity * p.price) AS TotalRevenue
FROM 
    categories c
JOIN 
    products p ON c.id = p.categories_id
JOIN 
    order_item ip ON p.id = ip.product_id
GROUP BY 
    c.name
ORDER BY 
    TotalRevenue DESC;